apiVersion: apps/v1
kind: Deployment
metadata:
  name: ghost-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ghost
  template:
    metadata:
      labels:
        app: ghost
    spec:
      containers:
      - name: ghost
        image: ghost:latest
        ports:
        - containerPort: 2368
        env:
        - name: url
          value: http://localhost:2368
        - name: database__client
          value: "mysql"
        - name: database__connection__host
          value: "mariadb"
        - name: database__connection__user
          value: "ghost"
        - name: database__connection__password  
          valueFrom:
            secretKeyRef:
              name: demo-secret
              key: password
        - name: database__connection__database
          value: "ghostdb"
        resources:
          limits:
            cpu: 900m
            memory: 1000Mi
          requests:
            cpu: 100m
            memory: 128Mi
        livenessProbe:
          httpGet:
            path: /ghost
            port: 2368
          initialDelaySeconds: 60
          periodSeconds: 30
    
        volumeMounts:
        - name: ghost-content-storage
          mountPath: /var/lib/ghost/content
      volumes:
      - name: ghost-content-storage
        persistentVolumeClaim:
          claimName: ghost-pvc

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mariadb-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mariadb
  template:
    metadata:
      labels:
        app: mariadb
    spec:
      containers:
      - name: mariadb
        image: mariadb:latest
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: demo-secret
              key: root-password
        - name: MYSQL_USER
          value: "ghost"
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: demo-secret
              key: password
        - name: MYSQL_DATABASE
          value: "ghostdb"
        volumeMounts:
        - name: mariadb-storage
          mountPath: /var/lib/mysql
        resources:
          limits:
            cpu: "1"
            memory: "1Gi"
          requests:
            cpu: "0.5"
            memory: "512Mi"
      volumes:
      - name: mariadb-storage
        persistentVolumeClaim:
          claimName: mariadb-pvc

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ghost-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mariadb-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---
apiVersion: v1
kind: Service
metadata:
  name: ghost-service
spec:
  selector:
    app: ghost
  ports:
  - protocol: TCP
    port: 2368
    targetPort: 2368
  type: LoadBalancer

---
apiVersion: v1
kind: Service
metadata:
  name: mariadb
spec:
  selector:
    app: mariadb
  ports:
  - protocol: TCP
    port: 3306
    targetPort: 3306
