name: Deploy

on:
  push:
    branches:
      - main  # Run on push to main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Install SOPS and Kubectl
        run: |
          sudo apt-get update
          sudo apt-get install -y sops kubectl

      - name: Setup Kubeconfig
        run: echo "${{ secrets.KUBECONFIG }}" | base64 -d > ~/.kube/config

      - name: Decrypt and Apply Secrets
        run: |
          ./decrypt-secrets.sh
          kubectl apply -f k8s-deployment.yaml
