name: Deploy

on:
  push:
    branches:
      - main 

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Install SOPS and Kubectl
        run: |
          sudo apt-get update
          sudo apt-get install -y kubectl
          SOPS_VERSION=$(curl --silent "https://api.github.com/repos/mozilla/sops/releases/latest" | grep '"tag_name":' | sed -E 's/.*"([^"]+)".*/\1/') # Fetch the latest version of SOPS
          curl -L "https://github.com/mozilla/sops/releases/download/${SOPS_VERSION}/sops-${SOPS_VERSION}.linux" -o sops
          chmod +x sops
          sudo mv sops /usr/local/bin/

      - name: Setup Kubeconfig
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.KUBECONFIG }}" | base64 -d > ~/.kube/config

      - name: Decrypt and Apply Secrets
        run: |
          chmod +x ./decrypt-secrets.sh
          ./decrypt-secrets.sh
          if [ -f k8s-deployment.yaml ]; then
            kubectl apply -f k8s-deployment.yaml
          else
            echo "k8s-deployment.yaml not found"
            exit 1
          fi
        shell: /usr/bin/bash -e {0}
